### PR TITLE
Manage roles and permissions

### PR DESCRIPTION
**Pull request by robmarch2**
This change includes:

- The ability to manage which roles are present in the system
- The ability to manage which users are assigned to the IS Admin role
- The ability to manage school roles

### CODE REVIEW

**Comment by dspeed2** [comment]
Hey Rob,

I've just cloned the Digirati repo and checked out the branch on my machine.  Everything builds \0/ but I'm missing at least one db table (Permissions).

At the meeting we had to discuss various things we spoke about providing sql for the schema changes (In my memory of this Daniel asked if we didn't trust hibernate update and we said we hadn't had great experience of it)

We've made a dir in the broker project to store release sql

./datavault-broker/src/main/resources/release-sql/3.2.0

If you had a sql file or files it wold be good if you could add them here.  If you don't have the file(s) I can probably create them.

I'm off again tomorrow so I probably won't get back you till Thursday if you respond tomorrow.

I'm hoping I'm not about to kick off an argument.

**Comment by robmarch2** [comment]
Hi David

That's a bit weird - hibernate created those tables for us in all our local and test environments, so it sounds like something's gone wrong for you with the auto import. We had to change the `hibernate.hbm2ddl.auto` property in `datavault-broker-root.xml` from "validate" to "update" to get it to work for us, and it got accidentally reverted out when I updated our fork with the latest changes from here around the time I made this PR, so depending on where your git head is, that could possibly explain it.

When everything works, it should create 4 tables named `Roles`, `Permissions`, `Role_assignments`, and `Role_permissions`. I'd guess that if it's indeed a problem with the auto import it won't have created any of them, so if you have any of them I'm possibly barking up the wrong tree here.

If we can't get it working for you via hibernate we'd be happy to add the creation of the tables as standalone scripts if that's your decision, but I think it's worth digging into why it's working for us but not for you a little bit more before we do that.

I'll be around on Slack between 10 and 6 most working days, so if you have any more problems with it feel free to ping me on there.

**Comment by WilliamPetit** [comment]
Hi Rob,

We voluntarily use 'validate' and not 'update' in the hibernate configuration.
As David was saying, we choose to not trust hibernate for dealing with db migrations and choose to do the db updates manually and keep track on every changes made to the database with SQL files.

We are aware there are existing tools for database versioned migrations like Flyway but we're just not using any at the moment.
When we had the meeting, we though it has been said that you will be using such tool and we were wondering if you'll have those SQL files already. But, as David said, if you don't that's also fine, we can create those SQL files ourself, it should not be a problem as it's usually easier to deal with new tables than with changes in existing tables.

Regards,
William

________________________________

**Comment by robmarch2** [comment]
Fair enough - I wasn't at the meeting so I wasn't aware that this had been agreed. I'll aim to push up the SQL scripts for creating those tables early afternoon today.

**Comment by dspeed2** [comment]
Thanks for the files.  I've been experimenting with the schema changes generated by hibernate and by your sql.  Everything works with the auto sql but the files didn't immediately load without errors.

I can also see differences in some of the fields in your files.  I'll slack you tomorrow if that is an issue.

I have been able to create a vault, deposit to it and retrieve and the new code looks fine.  I'm just waiting for the others who know more about these new features to decide if we can merge or if they want to see more first.

**Comment by robmarch2** [comment]
Ah - my bad. I got the script by running `SHOW CREATE TABLE tablename` for each of the tables in my local database, and it appears that a change from our current sprint crept in (the `assignedUserCount` field on `Roles`). I'll back that out just now so the script matches the models.

I'm on annual leave tomorrow so I'm afraid I won't be available on slack but if you've got any problems with this change I'm sure one of my colleagues would be happy to help. Also, just so you're aware we follow english bank holidays so no one will be around on Monday

**Comment by dspeed2** [comment]
Hey Rob,

Sorry I misread your comment on Thursday about stuff sneaking in that shouldn't be there.  I did read about you being off till Tuesday which is why I left things to now.

Ah I see you edited your comment. I didn't notice that till now (I was pretty confused for a bit!)

I've just committed to master the sql that was generated when I ran show create table on my local deploy after the update command changed my local schema.  The file is called roles.sql.EDINA you can use that to compare against your own one.  I've changed the default charset form latin1 but everything else was auto generated.

I was actually about to merge the request and deploy to demo.  I'll leave that till you comment tomorrow now.

**Comment by robmarch2** [comment]
Ah, I see what's happened. We've been using Maria DB for local development as it's less memory intensive and is supposed to be completely interchangeable with MySQL, but it seems that there's some subtle differences. I've replaced the contents of that script with the one you've provided, and we'll make sure to switch back to MySQL when generating such scripts in the future

**Pull request merged**
