### PR TITLE
RSS212-194 - Adding user roles to Pending Vault Creation page.

### PR DESCRIPTION
**Pull request by johnpinto1**
Selection_016
Firefox_Screenshot_2021-09-13T16-04-29 963Z

### CODE REVIEW

**Comment by dspeed2** [comment]
I've just checked this out and deployed it on my machine.  When I try to create a new pending vault the validation to enable / disable the next button on the affirmation page  isn't working anymore so I can't go any further.

Does that work for you? @johnpinto1 

I've cleared cache etc. but still not working

**Comment by johnpinto1** [comment]
@dspeed2 Let me check. I might not have checked that.

**Comment by johnpinto1** [comment]
@dspeed2 The usersFieldset.ftl is the problem when vault not yet created. Suspect it some null value checks.

**Comment by johnpinto1** [comment]
@dspeed2 Fixed issue. I am sure other bugs will appear.

**Pull request merged**
