### PR TITLE
RSS212-214 - Fix for Review Date cannot be set via calendar more than 30

### PR DESCRIPTION
**Pull request by johnpinto1**
years in future.

The change has been to set the defaults for the Datepicker to have a
minDate to be today and maxDate 30 years in future. Note the Review date
has minDate overriden to be 1 month from today.

### CODE REVIEW

**Comment by johnpinto1** [comment]
This may need further changes as requested.

**Review by dspeed2 — COMMENTED** [review]
If I manually type in a date more than 30 years in the future totally bypassing the date picker it is accepted (it will get rejected by the client side validation though).

We need to add something to catch this if the review date changes too.

**Comment by johnpinto1** [comment]
@dspeed2 Will fix that this afternoon.

**Comment by dspeed2** [comment]
I've ran these tests on deploys of origin/master-metadata-gui and origin/RSS212-214-add-js-review-date-less-30-yrs (after merging master-metadata-gui into it).

I'll be going out for a long dinner soon but we can talk about when I get back if you have time.  Basically we just want the tests that currently pass on master-metadata-gui to continue to pass and the one that currently fails when a date more than 30 years in the future will pass by disabling the next step button and putting up a message something like ""Invalid Review Date as the date must be less than 30 years in the future.”

I people have asked for other stuff in the various tickets we'll need to come up with some sort of compromise.

On origin/master-metadata-gui

If I create a new vault with

GED 2022-01-27
Retention policy Uni of Ed with minimum period of 3 years
Suggest review date is given as 2025-01-27 (3 years) (correct)
Fill in everything else
Change review date to less than 3 years get "Invalid Review Date as the date must be at least 3 years in the future.” Message and next step disabled (correct)
Change review date to 3 years or more in future next step enabled (correct)
Change review date to 2075-01-27 button still enabled (incorrect want similar message to must be at least 3 years in the future and next step disabled)
Change review date to 2020-01-27 (less than 3 years and in past) get "Invalid Review Date as the date must be at least 3 years in the future.” Message and next step disabled (correct)

GED 2022-01-27
Retention policy Tenovus with minimum period of 2 years
Suggest review date is given as 2025-01-27 (3 years) (correct)
Fill in everything else
Change review date to less than 3 years get "Invalid Review Date as the date must be at least 3 years in the future.” Message and next step disabled (correct even though min is 2 years)
Change review date to 3 years or more in future next step enabled (correct)
Change review date to 2075-01-27 button still enabled (incorrect)
Change review date to 2020-01-27 (less than 3 years and in past) get "Invalid Review Date as the date must be at least 3 years in the future.” Message and next step disabled (correct)

On origin/RSS212-214-add-js-review-date-less-30-yrs

GED 2022-01-27
Retention policy Uni of Ed with minimum period of 3 years
Suggest review date is given as 2025-01-27 (3 years) (correct)
Fill in everything else
Change review date to less than 3 years no error and next step enabled (incorrect)
Change review date to 3 years or more in future next step enabled (correct)
Change review date to 2075-01-27 button still enabled and date changed to 30 years no message (correctish)
Change review date to 2020-01-27 (less than 3 years and in past)  no message date changed to today (less than 3 years) next step enabled (incorrect)

**Comment by dspeed2** [comment]
Ok that seems much better :-). I'm going to merge it now cause I want to deploy it to Demo with other stuff but there are a couple of things we might want to improve

1) The year select box only ever shows a spread of 10 years as far as I can tell.  The 10 years change depending on what has been selected but I couldn't find a way to enter 29 years in the future with the select box, I had to type it in manually.  So perhaps it should be scrollable to 30 years?
2) Everything works fine with the correct error / warning message if you type something manually then change focus but if you hit enter with an invalid value it defaults to the best option (I've seen it put 3 years or 30 here depending on whether the input was less or more than the min / max) without a message saying we have rejected / changed the input.

**Comment by johnpinto1** [comment]
@dspeed2 You need to to go to end of the selection and it then pulls up a next set of years. You will need to do it do it several times to get to 30 years.

**Pull request merged**
