### PR TITLE
Adding SQL to insert 3 new schools

### PR DESCRIPTION
**Pull request by WilliamPetit**

### CODE REVIEW

**Comment by WilliamPetit** [comment]
you mean here: `datavault.Groups`
That the bd_name.table_name, I think I've tested the SQL on demo and it did work.
I've autogenerated it or else I would not have bothered adding db name. :)

**Comment by dspeed2** [comment]
> you mean here: `datavault.Groups`
> That the bd_name.table_name, I think I've tested the SQL on demo and it did work.
> I've autogenerated it or else I would not have bothered adding db name. :)

I noticed eventually.

**Comment by dspeed2** [comment]
We've made the changes on demo / live (I think) so lets just keep them in 3.9.0

**Comment by WilliamPetit** [comment]
I don't know about the directory. I'll add to the `import.sql` but I though it wasn't used anymore?

**Comment by dspeed2** [comment]
I've made a couple of quick changes just to tidy up.  I'll merge the next time we deploy to demo.

**Comment by dspeed2** [comment]
Hopefully I haven't messed anything up

**Pull request merged**
