### PR TITLE
RSS212-197: Adding validation of roles for pending vault creation.

### PR DESCRIPTION
**Pull request by johnpinto1**
- A method isUUN() to check if a text string is added to the
    UserLookupService class. This method is the used by the method isUUN()
    in the VaultsController.
 - We check that input values for NDMs and Depositors are valid UUNs by
    making an Ajax call to the isUUN() method of the VaultsController.
 - We disable the Next button in usersFieldset.ftl if there is a UUN
      validation error. (We plan to extend it further as we add new validation).
      We do this checking for error spans when the event
      'DOMSubtreeModified', attached to the Div enclosing the Role inputs, is fired.
-  We needed to trigger an "input" event when we selected UUN to detect a
    change in the input text. Which we need for our validation check above.

### CODE REVIEW

**Comment by dspeed2** [comment]
I've checked this out on my machine and deployed.  It works fine if the user selects and then clicks on another element but still allows invalid users if you type in Spiderman then go directly to the next button it skips the validation.

Don't know if we can make it do the validation with each char like it updates the list as you type.

**Comment by johnpinto1** [comment]
@dspeed2 Will try and look at this today.

**Comment by dspeed2** [comment]
Almost!

NDMs and Depositors worked fine for all the testing I did (well after I remembered to refresh the JS) but contact person doesn't work I suspect that is something to do with it not being a mandatory field.

We should check with Pauline but I also suspect we should add the validation to Owner UUN too.

I'm happy to merge what we have now but I'll wait till you are back on Monday in case you say otherwise.

This is only semi related I also noticed how you added the hidden fields without having to add them all manually we can maybe think about adding the max size as a property to datavault.properties at some point so it can easily be changed if ever required.

**Comment by johnpinto1** [comment]
@dspeed2 Pushed with making Owner UUN and Contact Person subject to UUN validation.

**Pull request merged**
