### PR TITLE
RSS212-57 - Fix sorting on Admin Billing and Vault pages

### PR DESCRIPTION
**Pull request by WilliamPetit**
Fixes the sorting on Vault and Billing admin page.
Replace Vault.getUser() by new RoleAndPermissions.getVaultOwner(VaultId).
Fix some Error thrown when owner was null (with orphan Vault)

### CODE REVIEW

**Comment by robintaylor** [comment]
One tiny wee question - In RolesAndPermissionsService you have introduced the UserDAO...

 return userDao.findById(ownerAssignment.getUserId());

Would it have been better to use the UsersService rather than the DAO directly? So...

return userService.getUser(ownerAssignment.getUserId());

I really don't know what is best practice so feel free to ignore this.

**Comment by WilliamPetit** [comment]
> One tiny wee question - In RolesAndPermissionsService you have introduced the UserDAO...
> 
> return userDao.findById(ownerAssignment.getUserId());
> 
> Would it have been better to use the UsersService rather than the DAO directly? So...
> 
> return userService.getUser(ownerAssignment.getUserId());
> 
> I really don't know what is best practice so feel free to ignore this.

I don't know what is the best practice but when I tried to use the service I had some issues and I saw that the service was already linked to multiple DAO so I assumed that it was the right thing to do.

**Comment by WilliamPetit** [comment]
Thinking about it might actually be better to use Service as if the way to get the user change then it only needs to be updated in the UserService. I've just tried and I didn't get any issue this time so if you want I can change it. :)

**Comment by dspeed2** [comment]
I think you are supposed to wrap a DAO in a service or manager class but I've never really understood why.  I seem to remember chat about a black box blah blah blah but when your service  method is literally "return Dao.stuff" it always seems waste of time to me.  Having said that if all the other stuff wraps a service around a DAO it would be better to have it all the same.

I haven't looked at any code in this review just adding to the lively debate

**Comment by WilliamPetit** [comment]
It's using UserService now, I also fixed a bug with the sorting on deposit page.

**Pull request merged**
