### PR TITLE
RSS022-258

### PR DESCRIPTION
**Pull request by robintaylor**

### CODE REVIEW

**Comment by dspeed2** [comment]
I checked this out on my machine ran mvn clean package, docker-compose build then docker-compose up -d and started a deposit.  I saw this in the worker log

workers_1               | 12:27:48,880  INFO main tasks.Deposit:65 - Deposit job - performAction()
workers_1               | 12:27:48,881  INFO main tasks.Deposit:66 - chunking: true
workers_1               | 12:27:48,881  INFO main tasks.Deposit:67 - chunks byte size: 10000000
workers_1               | 12:27:48,882  INFO main tasks.Deposit:68 - encryption: true
workers_1               | 12:27:48,882  INFO main tasks.Deposit:69 - encryption mode: GCM
workers_1               | 12:27:49,012 DEBUG main queue.EventSender:97 - Sent 523 bytes
workers_1               | 12:27:49,014 DEBUG main queue.EventSender:98 - Sent message body '{"id":null,"message":"Job states: 6","retrieveId":null,"eventClass":"org.datavaultplatform.common.event.InitStates","nextState":null,"timestamp":"2018-11-08T12:27:48.897Z","sequence":0,"persistent":false,"depositId":"f6a3f410-3e1e-4c8b-94c4-3aea509898ae","vaultId":null,"jobId":"e3d7ea14-3909-4fdb-b5c3-9ab0d758e005","userId":"dspeed2","agent":"136@c1da586b722f","remoteAddress":null,"userAgent":null,"agentType":"WORKER","states":["Calculating size","Transferring","Packaging","Storing in archive","Verifying","Complete"]}'
workers_1               | 12:27:49,102 DEBUG main queue.EventSender:97 - Sent 423 bytes
workers_1               | 12:27:49,102 DEBUG main queue.EventSender:98 - Sent message body '{"id":null,"message":"Deposit started","retrieveId":null,"eventClass":"org.datavaultplatform.common.event.deposit.Start","nextState":0,"timestamp":"2018-11-08T12:27:49.053Z","sequence":1,"persistent":true,"depositId":"f6a3f410-3e1e-4c8b-94c4-3aea509898ae","vaultId":null,"jobId":"e3d7ea14-3909-4fdb-b5c3-9ab0d758e005","userId":"dspeed2","agent":"136@c1da586b722f","remoteAddress":null,"userAgent":null,"agentType":"WORKER"}'
workers_1               | 12:27:49,130  INFO main tasks.Deposit:102 - bagID: d21e2b80-be52-46aa-9b37-20b7a036b1d9
workers_1               | Construct SFTPFileSystem...
workers_1               | casting byte[]...
workers_1               | done!
workers_1               | SFTPFileSystem created...
workers_1               | 12:27:49,164  INFO main tasks.Deposit:128 - Connected to user store: ee31d12e-5c60-4ef7-9470-84bce9ea081c, class: org.datavaultplatform.common.storage.impl.SFTPFileSystem
workers_1               | fileStorePath: ee31d12e-5c60-4ef7-9470-84bce9ea081c/CNS01_20170914.xml
workers_1               | fileUploadPath: 638624a3-ec49-4165-ac67-7b077bf74591
workers_1               | Exception in thread "main" java.lang.NoClassDefFoundError: oracle/cloudstorage/ftm/exception/ClientException
workers_1               |     at java.lang.Class.forName0(Native Method)
workers_1               |     at java.lang.Class.forName(Class.java:264)
workers_1               |     at org.datavaultplatform.worker.tasks.Deposit.performAction(Deposit.java:149)
workers_1               |     at org.datavaultplatform.worker.queue.Receiver.receive(Receiver.java:250)
workers_1               |     at org.datavaultplatform.worker.WorkerInstance.main(WorkerInstance.java:49)
workers_1               | Caused by: java.lang.ClassNotFoundException: oracle.cloudstorage.ftm.exception.ClientException
workers_1               |     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
workers_1               |     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
workers_1               |     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
workers_1               |     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
workers_1               |     ... 5 more

The deposit didn't fail but that is another issue.  I dunno if I needed to do something else before I deployed.

**Comment by dspeed2** [comment]
Oh forgot to say I switched back to master did the same steps and the deploy worked.

**Comment by dspeed2** [comment]
I still get the same or similar error

nksDigest":null,"redeliver":false}'
workers_1               | 14:50:41,897  INFO main tasks.Deposit:65 - Deposit job - performAction()
workers_1               | 14:50:41,899  INFO main tasks.Deposit:66 - chunking: true
workers_1               | 14:50:41,899  INFO main tasks.Deposit:67 - chunks byte size: 10000000
workers_1               | 14:50:41,899  INFO main tasks.Deposit:68 - encryption: true
workers_1               | 14:50:41,900  INFO main tasks.Deposit:69 - encryption mode: GCM
workers_1               | 14:50:42,032 DEBUG main queue.EventSender:97 - Sent 523 bytes
workers_1               | 14:50:42,033 DEBUG main queue.EventSender:98 - Sent message body '{"id":null,"message":"Job states: 6","retrieveId":null,"eventClass":"org.datavaultplatform.common.event.InitStates","nextState":null,"timestamp":"2018-11-08T14:50:41.902Z","sequence":0,"persistent":false,"depositId":"f6cc6b91-b634-4bd2-b422-9b10973bebe8","vaultId":null,"jobId":"6e908884-e6b5-4ea7-a7ed-047a6a79608c","userId":"dspeed2","agent":"129@fdcd660aabc8","remoteAddress":null,"userAgent":null,"agentType":"WORKER","states":["Calculating size","Transferring","Packaging","Storing in archive","Verifying","Complete"]}'
workers_1               | 14:50:42,099 DEBUG main queue.EventSender:97 - Sent 423 bytes
workers_1               | 14:50:42,101 DEBUG main queue.EventSender:98 - Sent message body '{"id":null,"message":"Deposit started","retrieveId":null,"eventClass":"org.datavaultplatform.common.event.deposit.Start","nextState":0,"timestamp":"2018-11-08T14:50:42.067Z","sequence":1,"persistent":true,"depositId":"f6cc6b91-b634-4bd2-b422-9b10973bebe8","vaultId":null,"jobId":"6e908884-e6b5-4ea7-a7ed-047a6a79608c","userId":"dspeed2","agent":"129@fdcd660aabc8","remoteAddress":null,"userAgent":null,"agentType":"WORKER"}'
workers_1               | 14:50:42,119  INFO main tasks.Deposit:102 - bagID: 7d39e9b8-f994-4c1c-99df-7f730d2d2d15
workers_1               | Construct SFTPFileSystem...
workers_1               | casting byte[]...
workers_1               | done!
workers_1               | SFTPFileSystem created...
workers_1               | 14:50:42,139  INFO main tasks.Deposit:128 - Connected to user store: ee31d12e-5c60-4ef7-9470-84bce9ea081c, class: org.datavaultplatform.common.storage.impl.SFTPFileSystem
workers_1               | fileStorePath: ee31d12e-5c60-4ef7-9470-84bce9ea081c/CNS01_20170914.xml
workers_1               | fileUploadPath: 28a4764c-68e2-4a35-b98f-ed4480d9758a
workers_1               | Exception in thread "main" java.lang.NoClassDefFoundError: oracle/cloudstorage/ftm/exception/ClientException
workers_1               | 	at java.lang.Class.forName0(Native Method)
workers_1               | 	at java.lang.Class.forName(Class.java:264)
workers_1               | 	at org.datavaultplatform.worker.tasks.Deposit.performAction(Deposit.java:149)
workers_1               | 	at org.datavaultplatform.worker.queue.Receiver.receive(Receiver.java:250)
workers_1               | 	at org.datavaultplatform.worker.WorkerInstance.main(WorkerInstance.java:49)
workers_1               | Caused by: java.lang.ClassNotFoundException: oracle.cloudstorage.ftm.exception.ClientException
workers_1               | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
workers_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
workers_1               | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
workers_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
workers_1               | 	... 5 more

**Comment by dspeed2** [comment]
Oh I might have been a commit behind, I'll try again with the latest commit.

**Comment by dspeed2** [comment]
Still bust giving up for today!

**Comment by WilliamPetit** [comment]
One of the issue I had when trying to fix `docker-enhancement-and-travix-fix` is that I wasn't using version 1.0 for the Oracle package. You might want to try it again with those changes.

**Comment by WilliamPetit** [comment]
I tried the solution I was suggesting and it doesn't work. :(
Looks like having just the dependency doesn't actually install it in the `.m2/repository` folder and even if the build passes, at run time the worker throws an exception:
```
workers_1_6387b96e7078  | Exception in thread "main" java.lang.NoClassDefFoundError: oracle/cloudstorage/ftm/exception/ClientException
workers_1_6387b96e7078  | 	at java.lang.Class.forName0(Native Method)
workers_1_6387b96e7078  | 	at java.lang.Class.forName(Class.java:264)
workers_1_6387b96e7078  | 	at org.datavaultplatform.worker.tasks.Deposit.performAction(Deposit.java:149)
workers_1_6387b96e7078  | 	at org.datavaultplatform.worker.queue.Receiver.receive(Receiver.java:250)
workers_1_6387b96e7078  | 	at org.datavaultplatform.worker.WorkerInstance.main(WorkerInstance.java:49)
workers_1_6387b96e7078  | Caused by: java.lang.ClassNotFoundException: oracle.cloudstorage.ftm.exception.ClientException
workers_1_6387b96e7078  | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
workers_1_6387b96e7078  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
workers_1_6387b96e7078  | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
workers_1_6387b96e7078  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
workers_1_6387b96e7078  | 	... 5 more

```

**Pull request closed without merging**
