### PR TITLE
Ds 127 20180322

### PR DESCRIPTION
**Pull request by dspeed2**
Request to merge in TSM / S3 with chunking option into UOE.  Once this has been agreed and merged we can merge into master.

### CODE REVIEW

**Comment by WilliamPetit** [comment]
Just started looking at it and I think you pushed the change of `datavault-assembly/src/datavault-home/config/datavault.properties` by mistake?
It would actually be useful but I would replace your user name with something else:
`sftp.rootPath = /sg/datastore/edina/users/<username>`

**Comment by WilliamPetit** [comment]
Same for `datavault-broker/src/main/webapp/WEB-INF/datavault-broker-root.xml`, did you change `hibernate.hbm2ddl.auto` to `create` for a reason? I would prefer to leave the file like it was to avoid conflict with my local repo as I also changed it on my machine...

I saw several commented out stuff, just wondering if you left it because you want to keep it or you just forgot to delete it? Thinking of stuff like the use of `json` in 'datavault-worker/src/main/java/org/datavaultplatform/worker/tasks/Deposit.java' for example.

Apart from that it looks good but I'd like to test it on my machine before merging if you are not waiting for it? I'll probably do that next week cause I'm in the middle of something with the encryption that I'd like to finish first...

**Comment by dspeed2** [comment]
The JSON was something I was doing but it turned out I didn't need to so that will get removed the next time I do a clean up.  The hibernate config is a type I meant to put it back to create-drop after temp changing it to update.  I'll revert that soon, I've already committed an update to fix the sftp filename.

**Comment by WilliamPetit** [comment]
Could not test it on my machine as I'm having problem with Vbox on my machine.
But I had a look at the diff and it looks good so going to merge it.

**Comment by WilliamPetit** [comment]
Actually just saw I just needed to approve the merge request, so I'll let you press the scary button and merge it with uoe and master. :)

**Pull request merged**
