### PR TITLE
#LUC070-113 Added retry functionality to deposit file size check and copy from user space

### PR DESCRIPTION
**Pull request by dspeed2**
Added retry functionality to deposit file size check and copy from user space.   Also added it to the retrieve free space check too

1) Added new BaseTwoSpeedRetryTask.java class to hold the TwoSpeedConfig methods used by both retrieve and deposit. 2) Updated the Deposit calculateTotalDepositSize & copyFromUserFS methods to use the twoSpeedRetryTemplate code 3) Updated the Retrieve calculateFreeSpace method to use the twoSpeedRetryTemplate code 4) Updated the RetrieveTest so the test for failing to calculate size now expects the correct error messsge.

I still need to add tests to the DepositTest (which I assume exists)

One thing is that one of the RetrieveTests now triggers the retry functionality for checking the free space so the test now takes 10 mins to complete.  We might want to see about reducing the wait time for tests.

### CODE REVIEW

**Comment by davidhay** [comment]
As we are now retrying UserFs operations in both Retrieve and Deposit, decided to change change the property names to reflect this.
image

Also changed DepositController in Broker to set these properties for Deposit Tasks.
image

Made some changes to 
org.datavaultplatform.worker.tasks.RetrieveTest#getRetrieveForTest
to reduce the retry delay to 50ms to get rid of extra 10mins of test time.

**Comment by davidhay** [comment]
There is no test code specifically for  Deposit Task (org.datavaultplatform.worker.tasks.Deposit).
Creating a test is not a small piece of work as Deposit.java is a large java file (> 1,000 lines)

**Comment by dspeed2** [comment]
I'm fine with the additional changes, everything new deploys on my machine and deposits / retrieves still work :-)

I haven't ran the tests yet but I'm about to do that and expecting them to pass.

Also fine with the lack of a deposit task test.

**Comment by davidhay** [comment]
I'm pretty sure all the tests pass - I don't think you need to write any extra tests for the retries in Retrieves.
The reason the Retrieve test was taking 10 minutes was that the the retry **was** working :-)

**Comment by dspeed2** [comment]
Yep the tests all did pass :-)

I knew the retrieve tests were showing it worked I just wanted to tweak the sleep time (which you've done) while the test ran and confirm you were happy with just updating the expected error message.

I think we are both happy enough to merge when we are ready.

**Review by davidhay — APPROVED** [review]
Tests pass. Okay for merging.

**Pull request merged**
