### PR TITLE
UTF-8 fixes and increased text field sizes

### PR DESCRIPTION
**Pull request by tomhigginsuom**
**Fixes to allow UTF-8 support in the DB**

The main change is that when using the full 4-byte UTF-8 character encoding in MySQL (utf8mb4) the DB engine assumes the worst case for character lengths, which means that keys have to be shorted in a UTF-8 database (e.g. 255 is too large since 255 * 4 is larger than the MySQL max key size of 767 bytes). 

Most of our keys are UUIDs, which I've defined as 36 character fields.

Where strings are used as keys I've defined a length of 180 (180 * 4 = 720 which is less than the limit of 767).

All other string fields I've redefined as TEXT (65k characters). Some of these can probably be shortened if needed.

**Tomcat**

I've defined character encoding filters in web.xml for both the webapp and the broker. These need to be the first filters in the config to work properly (and they'll force input to be treated as UTF-8).

**datavault.properties**

Your connection string needs to include the `useUnicode` parameter:
`dbURL = localhost:3306/datavault?useUnicode=true`

**MySQL config**

Some config changes are required in MySQL to support UTF-8.

The database needs to be created with the correct encoding:
`CREATE DATABASE datavault CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`

Edit /etc/mysql/my.cnf and under the `[mysqld]` section add the following:
```
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

You'll need to restart MySQL for these changes to take effect:
```sudo service mysql restart```

**Testing**

A useful set of UTF-8 strings for testing is:
https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt

For example:
`ᚻᛖ ᚳᚹᚫᚦ ᚦᚫᛏ ᚻᛖ ᛒᚢᛞᛖ ᚩᚾ ᚦᚫᛗ ᛚᚪᚾᛞᛖ ᚾᚩᚱᚦᚹᛖᚪᚱᛞᚢᛗ ᚹᛁᚦ ᚦᚪ ᚹᛖᛥᚫ`

### CODE REVIEW

**Comment by stuartlewis** [comment]
Isn't working for me - I need to go through all my configs to make sure I've got it all right (it could be mysql: I've got a funny mac installation of it)

**Comment by tomhigginsuom** [comment]
Hi Stuart,

What sort of problem are you seeing? Errors in Hibernate or bad characters (e.g. "?????")?

When I was testing this I found that the majority of the issues were in the DB - you might want to try dropping and re-creating your database by hand:
```
drop database datavault;
CREATE DATABASE datavault CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
```

**Comment by stuartlewis** [comment]
Hi Tom,

Code is good, just the question marks are persisting.  I dropped and re-created DB, but that didn't help.  I'll dig more tonight.

Thanks,

Stuart

**Comment by stuartlewis** [comment]
I wonder if there is a way to issue an SQL query to check that my.cnf is correctly configured and the setting picked-up?

**Comment by tomhigginsuom** [comment]
One trick with the my.cnf thing is that the settings really do need to be in the [mysqld] block or they don't get picked up.

You could try checking the following:

```
mysql> SHOW FULL COLUMNS FROM Vaults;
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| Field                      | Type         | Collation          | Null | Key | Default | Extra | Privileges                      | Comment |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
| id                         | varchar(36)  | utf8mb4_unicode_ci | NO   | PRI | NULL    |       | select,insert,update,references |         |
| creationTime               | datetime     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| description                | text         | utf8mb4_unicode_ci | YES  |     | NULL    |       | select,insert,update,references |         |
| name                       | text         | utf8mb4_unicode_ci | NO   |     | NULL    |       | select,insert,update,references |         |
| retentionPolicyExpiry      | datetime     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| retentionPolicyLastChecked | datetime     | NULL               | YES  |     | NULL    |       | select,insert,update,references |         |
| retentionPolicyStatus      | int(11)      | NULL               | NO   |     | NULL    |       | select,insert,update,references |         |
| vaultSize                  | bigint(20)   | NULL               | NO   |     | NULL    |       | select,insert,update,references |         |
| version                    | bigint(20)   | NULL               | NO   |     | NULL    |       | select,insert,update,references |         |
| dataset_id                 | varchar(180) | utf8mb4_unicode_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| group_id                   | varchar(180) | utf8mb4_unicode_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| retentionPolicy_id         | varchar(180) | utf8mb4_unicode_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
| user_id                    | varchar(36)  | utf8mb4_unicode_ci | YES  | MUL | NULL    |       | select,insert,update,references |         |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+---------+
```

```
mysql> SHOW VARIABLES LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | utf8    |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8    |
+--------------------------+---------+
7 rows in set (0.00 sec)
```

**Comment by stuartlewis** [comment]
Thanks - I'll try that.

**Comment by stuartlewis** [comment]
Working now :)

It appears that it wasn't reading my config file, so it was making up a version.  I copied mine into the default location of /etc/my.cnf and it works great now!

**Pull request merged**
