### PR TITLE
Reporting changes

### PR DESCRIPTION
**Pull request by ayeshasultanaa**
Merge request - This includes the work done for saving the project Id on Vault creation and calculating the project size and Billing screens

### CODE REVIEW

**Comment by WilliamPetit** [comment]
It looks like existing Vaults will generate an error cause they won't have a Billing associated with them. We need to generate missing Billing record somehow...

**Comment by WilliamPetit** [comment]
Looks like Editing doesn't work I'm getting an Error:

```
Error code 405 returned for /datavault-webapp/admin/billing/updateBillingDetails with message:
Method Not Allowed
```

```
web_1_92dc43ae4c0d      | Calling Broker with url:http://broker:8080/datavault-broker/admin/billing/6a7bb42e-d7d1-4f0c-b444-7b6ce98ebd1e Method:GET
web_1_92dc43ae4c0d      | -----------Comments---------null
web_1_92dc43ae4c0d      | 13:38:09,018  WARN http-apr-8080-exec-9 servlet.PageNotFound:210 - Request method 'POST' not supported

```

**Comment by WilliamPetit** [comment]
My last 2 commit should fix the missing projectID error and Editing on the Billing page.

**Comment by dspeed2** [comment]
I've finally managed to look at this.

I think there is stuff in ExternalMetadataService getPureProjectIds and getPureProjectId which is redundant I'll probably remove that before I approve.

i.e. I don't think we need

public Map<String, String> getPureProjectIds() {
    	Map<String, String> projectIds = new HashMap<>();
    	if (this.metadataProvider instanceof PureFlatFileProvider) {
    		projectIds = metadataProvider.getPureProjectIds();
    	} else {
    		//get from MockProvider
    		projectIds = metadataProvider.getPureProjectIds();
    	}
    	return projectIds;
    }

this should be the same
public Map<String, String> getPureProjectIds() {
    	Map<String, String> projectIds = metadataProvider.getPureProjectIds();;
    	return projectIds;
    }

and something similar for getPureProjectId.

I'm also confused about what exactly is finished in the Billing when I edit the billing info for a Vault it displays on the page but it isn't persisted in the DB so when move away the edit is lost.

**Pull request merged**
